import os

# Import the SCons environment
Import('env')

# Define paths for source files and build
src_dir = 'src'
build_dir = 'bin'

# Add source files to the build environment
env.add_source_files(src_dir, '*.cpp')
env.add_source_files(src_dir, '*.mm')

# Define the output directory
env.Program(target=build_dir + '/youtubedl_ios_plugin', source=Glob(src_dir + '/*.cpp'))
